# docker build -t vini8cs/polars_matplotlib:1.0 .
FROM mambaorg/micromamba:ubuntu22.04

USER root

ENV MAMBA_DOCKERFILE_ACTIVATE=1 \
    DEBIAN_FRONTEND=noninteractive \
    MAMBA_ROOT_PREFIX=/opt/conda

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    wget \
    git \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libmagic-dev \
    libcurl4-openssl-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN micromamba clean --all \
    && micromamba install -y -n base pip=25.0 \
    && pip install --no-cache-dir polars==1.29.0 \
    && pip install --no-cache-dir matplotlib==3.10.3 \
    && pip install --no-cache-dir pyarrow==20.0.0 \
    && pip install --no-cache-dir pandas==2.2.3 \
    && micromamba env export --name base > environment.lock \
    && echo ">> CONDA_LOCK_START" \
    && cat environment.lock \
    && echo "<< CONDA_LOCK_END" \
    && micromamba clean -a -y

ENV PATH="$MAMBA_ROOT_PREFIX/bin:$PATH"
